### ISSUE TITLE
dev-util/idea-community ebuilds contain the list of non-existing JBR binary files

### ISSUE THREAD

**Issue by master-kosm** [tmacedo/portage#16]
dev-util/idea-community ebuilds try to set permissions of JBR binary files over an irrelevant list:
```
fperms 755 "${dir}"/"$CUSTOM_JRE_DIR"/bin/{java,jjs,keytool,orbd,pack200,policytool,rmid,rmiregistry,servertool,tnameserv,unpack200}
```
After renaming of `CUSTOM_JRE_DIR` in the most recent ebuild 2019.3.1.193.5662.53, it leads to the installation error looking akin:
```
chmod: cannot access '/var/tmp/portage/dev-util/idea-community-2019.3.1.193.5662.53/image/opt/idea-community-201bin/orbd': No such file or directory
chmod: cannot access '/var/tmp/portage/dev-util/idea-community-2019.3.1.193.5662.53/image/opt/idea-community-201bin/policytool': No such file or directory
chmod: cannot access '/var/tmp/portage/dev-util/idea-community-2019.3.1.193.5662.53/image/opt/idea-community-201bin/servertool': No such file or directory
chmod: cannot access '/var/tmp/portage/dev-util/idea-community-2019.3.1.193.5662.53/image/opt/idea-community-201bin/tnameserv': No such file or directory
```

**Comment by tmacedo** [comment]
Sorry for the delay in replying, have been quite busy lately. The support for jbr 2019.3 on this build was a bit poor as it was pretty much reusing the earlier jre support. I "switched" the ebuild for a copy of the one in the main gentoo portage tree which is now updated to support jbr, I'll keep updating it as the gentoo tree tends to lag behind a bit.

**Comment by tmacedo** [comment]
Anyway, this should be solved now but the use flag changed from `custom-jdk` to `jbr8` and `jbr11`.

Thank you for reporting!
