### ISSUE TITLE
bup with python3.9

### ISSUE THREAD

**Issue by piotr5** [tmacedo/portage#17]
gentoo now uses python-3.9 and here =app-backup/bup-0.31.0::tmacedo fails to compile with the error
`_helpers.c:359:13: error: conflicting types for ‘Py_GetArgcArgv’; have ‘void(int *, char ***)’`
and that has been already fixed in its debian version:
https://bugs.debian.org/972763
not sure where to find the solution itself, but maybe create a patch?

**Comment by tmacedo** [comment]
Hi Piotr,

I pushed a new ebuild, also updating to 0.32.0. It seems to be working for me with python 3.9 but please let me know if it doesn't.
