### ISSUE TITLE
HipChat: Missing shared library

### ISSUE THREAD

**Issue by au-phiware** [tmacedo/portage#5]
Thanks for writing the ebuild for hipchat! However, when I attempt to execute `hipchat` I encounter this message:

    hello 0.660954
    /usr/bin/hipchat: error while loading shared libraries: libgstapp-0.10.so.0: cannot open shared object file: No such file or directory

AFAIK `libgstapp-0.10.so.0` should be apart of media-libs/gstreamer, but I have `media-libs/gstreamer-0.10.36-r2:0.10::gentoo`.

I suspect there's something else missing(?)

**Comment by tmacedo** [comment]
Hi,

It's part of media-libs/gst-plugins-base.

I added the dependency to the ebuild, let me know if it works for you!

**Comment by au-phiware** [comment]
My apologies for the long delay, I sync'ed your overlay today, emerged =net-im/hipchat-2.2.1388-r1 but it appears that media-libs/gst-plugins-base-1.4.5 was already installed and I'm still getting the same message... Should I try media-libs/gst-plugins-base-0.10.36-r2?

Here are the USE flags:

    media-libs/gst-plugins-base-1.4.5:1.0::gentoo  USE="X alsa introspection nls ogg orc pango vorbis -ivorbis -theora" ABI_X86="(64) -32 (-x32)"

**Comment by au-phiware** [comment]
I tried media-libs/gst-plugins-base-0.10.36-r2 (slot 0.10) and it worked!

**Comment by tmacedo** [comment]
Updated! Sorry about that.
