### ISSUE TITLE
net-im/slack-desktop-bin dependencies

### ISSUE THREAD

**Issue by otselnik** [tmacedo/portage#6]
Hello, slack depends on net-print/cups.
```
#ldd /usr/bin/slack
...
	libcups.so.2 => not found
...
```
Could you add it to ebuild?
Thanks.

**Comment by tmacedo** [comment]
Thanks for the report, I just published an updated ebuild. I mapped the dependencies of the ubuntu package to gentoo but I suppose cups is part of every ubuntu install so it wasn't there.

Regards,
Tiago
