### ISSUE TITLE
cutegram-9999 unable to build

### ISSUE THREAD

**Issue by vandr0iy** [tmacedo/portage#8]
cutegram-9999 does not build because of the fact that asemantools@91bf14b for some reason is unable to pull in the git tree at Aseman-Land/aseman-qt-tools.
is it fixable by editing the ebuild, or I should open an issue at the aseman's repo at https://github.com/Aseman-Land/Cutegram/tree/master/Cutegram ?

**Comment by tmacedo** [comment]
Sorry, that it took me *so* long to look into this but it's now fixed.
